name: Vault Dev Test

on:
  workflow_dispatch:

jobs:
  test-vault:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vault CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -fsSL https://releases.hashicorp.com/vault/1.18.1/vault_1.18.1_linux_amd64.zip -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
          vault --version

      - name: Start Vault DEV server (in background)
        run: |
          export VAULT_DEV_ROOT_TOKEN_ID=my-dev-token
          nohup vault server -dev -dev-root-token-id="$VAULT_DEV_ROOT_TOKEN_ID" > vault.log 2>&1 &
          echo "Esperando 3 segundos a que Vault arranque..."
          sleep 3

      - name: Set Vault env vars
        run: |
          echo "VAULT_ADDR=http://127.0.0.1:8200" >> $GITHUB_ENV
          echo "VAULT_TOKEN=my-dev-token" >> $GITHUB_ENV

      - name: Write a secret to Vault
        run: |
          vault kv put secret/prueba username="admin" password="1234"

      - name: List secrets
        run: |
          vault kv list secret/

      - name: Read secret
        run: |
          vault kv get secret/prueba
